from __future__ import annotations

from decimal import Decimal

DEFAULT_MAX_VENUE_SPREAD = Decimal("0.05")
DEFAULT_MIN_BUY_SIZE = Decimal("10")
DEFAULT_MIN_DEPTH_SIZE = Decimal("50")
DEFAULT_DEPTH_WINDOW = Decimal("0.03")
DEFAULT_MIN_EDGE = Decimal("0")
DEFAULT_MIN_FEE_ADJUSTED_EDGE = Decimal("0.01")

DEFAULT_SIGNAL_LOOKBACK_MINUTES = 10
DEFAULT_MIN_MID_EDGE = Decimal("0")
DEFAULT_MIN_POLY_MID_MOVE = Decimal("0")
DEFAULT_MIN_POLY_OI_DELTA = Decimal("0")
DEFAULT_MIN_POLY_VOLUME_DELTA = Decimal("0")
DEFAULT_MAX_KALSHI_MID_MOVE = Decimal("1")

DEFAULT_DISCOVERY_PRICE_VALIDATION_THRESHOLD = Decimal("0.03")
